# Generated by Django 3.2.2 on 2021-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='place',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
