# Generated by Django 3.2.2 on 2021-07-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0003_register_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='mobile_number',
        ),
    ]
