# Generated by Django 3.2.2 on 2021-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0004_remove_register_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mobile_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
