# Generated by Django 3.2.2 on 2021-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0005_register_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='registersecondtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
