# Generated by Django 3.2.1 on 2021-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0008_userregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
