# Generated by Django 3.2.2 on 2021-07-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0009_auto_20210727_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
