# Generated by Django 3.2.2 on 2021-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0010_alter_userregister_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='gender',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
