# Generated by Django 3.2.2 on 2021-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0012_auto_20210728_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')]),
        ),
    ]
