# Generated by Django 3.2.2 on 2021-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0013_alter_userregister_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
