# Generated by Django 3.2.2 on 2021-07-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0014_auto_20210728_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregister',
        ),
    ]
