# Generated by Django 3.2.1 on 2021-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0016_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
