# Generated by Django 3.2.1 on 2021-08-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0017_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='firstname',
        ),
    ]
