# Generated by Django 3.2.1 on 2021-08-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0019_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
