# Generated by Django 3.2.1 on 2021-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0020_doctors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
