# Generated by Django 3.2.1 on 2021-08-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0022_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file',
            new_name='files',
        ),
    ]
