# Generated by Django 3.2.1 on 2021-08-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0023_rename_file_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='files',
            new_name='filess',
        ),
    ]
