# Generated by Django 3.2.1 on 2021-08-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0024_rename_files_filess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filess',
        ),
    ]
