# Generated by Django 3.2.1 on 2021-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0026_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
