# Generated by Django 3.2.1 on 2021-09-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0027_ajax'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ajax',
            new_name='ajaxx',
        ),
    ]
